language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

before_install:
    - sudo apt update
    - sudo apt install -y protobuf-compiler

install:
    - pip install -U platformio
    - platformio update

script:
    - sh build-and-test.sh
