language: python
python:
    - "2.7"

dist: bionic
addons:
    apt:
        packages:
        - protobuf-compiler
        - python3-protobuf

sudo: false
cache:
    directories:
        - "~/.platformio"

install:
    - pip install -U platformio
    - platformio update

script:
    - sh build-and-test.sh
