/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.4-dev */

#ifndef PB_DOWNLINK_PROTO_MESSAGES_PB_H_INCLUDED
#define PB_DOWNLINK_PROTO_MESSAGES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _downlink_proto_AnalogMetrics {
    float analog_0;
    float analog_1;
    float analog_2;
    float analog_3;
} downlink_proto_AnalogMetrics;

typedef struct _downlink_proto_DigitalMetrics {
    bool digital_0;
    bool digital_1;
    bool digital_2;
    bool digital_3;
    bool digital_4;
} downlink_proto_DigitalMetrics;

typedef struct _downlink_proto_IMUMetrics {
    float euler_x;
    float euler_y;
    float euler_z;
    float quat_a;
    float quat_b;
    float quat_c;
    float omega_x;
    float omega_y;
    float omega_z;
    float magnitude_x;
    float magnitude_y;
    float magnitude_z;
    float temperature;
} downlink_proto_IMUMetrics;

typedef struct _downlink_proto_PowerSupplyMetrics {
    float temperature_v0;
    float temperature_v1;
    float level_3v3;
    float level_5v0;
} downlink_proto_PowerSupplyMetrics;

typedef struct _downlink_proto_SpaceComputerMetrics {
    float power_voltage;
    float power_current;
    float temperature_die;
} downlink_proto_SpaceComputerMetrics;

typedef struct _downlink_proto_Timestamp {
    int32_t month;
    int32_t day;
    int32_t year;
    int32_t hour;
    int32_t minute;
    int32_t second;
} downlink_proto_Timestamp;

typedef struct _downlink_proto_SystemMetrics {
    bool has_time;
    downlink_proto_Timestamp time;
    bool delayed;
    bool has_power_supply;
    downlink_proto_PowerSupplyMetrics power_supply;
    bool has_computer;
    downlink_proto_SpaceComputerMetrics computer;
    bool has_imu;
    downlink_proto_IMUMetrics imu;
    bool has_digital;
    downlink_proto_DigitalMetrics digital;
    bool has_analog;
    downlink_proto_AnalogMetrics analog;
} downlink_proto_SystemMetrics;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define downlink_proto_DigitalMetrics_init_default {0, 0, 0, 0, 0}
#define downlink_proto_AnalogMetrics_init_default {0, 0, 0, 0}
#define downlink_proto_Timestamp_init_default    {0, 0, 0, 0, 0, 0}
#define downlink_proto_PowerSupplyMetrics_init_default {0, 0, 0, 0}
#define downlink_proto_IMUMetrics_init_default   {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define downlink_proto_SpaceComputerMetrics_init_default {0, 0, 0}
#define downlink_proto_SystemMetrics_init_default {false, downlink_proto_Timestamp_init_default, 0, false, downlink_proto_PowerSupplyMetrics_init_default, false, downlink_proto_SpaceComputerMetrics_init_default, false, downlink_proto_IMUMetrics_init_default, false, downlink_proto_DigitalMetrics_init_default, false, downlink_proto_AnalogMetrics_init_default}
#define downlink_proto_DigitalMetrics_init_zero  {0, 0, 0, 0, 0}
#define downlink_proto_AnalogMetrics_init_zero   {0, 0, 0, 0}
#define downlink_proto_Timestamp_init_zero       {0, 0, 0, 0, 0, 0}
#define downlink_proto_PowerSupplyMetrics_init_zero {0, 0, 0, 0}
#define downlink_proto_IMUMetrics_init_zero      {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define downlink_proto_SpaceComputerMetrics_init_zero {0, 0, 0}
#define downlink_proto_SystemMetrics_init_zero   {false, downlink_proto_Timestamp_init_zero, 0, false, downlink_proto_PowerSupplyMetrics_init_zero, false, downlink_proto_SpaceComputerMetrics_init_zero, false, downlink_proto_IMUMetrics_init_zero, false, downlink_proto_DigitalMetrics_init_zero, false, downlink_proto_AnalogMetrics_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define downlink_proto_AnalogMetrics_analog_0_tag 1
#define downlink_proto_AnalogMetrics_analog_1_tag 2
#define downlink_proto_AnalogMetrics_analog_2_tag 3
#define downlink_proto_AnalogMetrics_analog_3_tag 4
#define downlink_proto_DigitalMetrics_digital_0_tag 1
#define downlink_proto_DigitalMetrics_digital_1_tag 2
#define downlink_proto_DigitalMetrics_digital_2_tag 3
#define downlink_proto_DigitalMetrics_digital_3_tag 4
#define downlink_proto_DigitalMetrics_digital_4_tag 5
#define downlink_proto_IMUMetrics_euler_x_tag    1
#define downlink_proto_IMUMetrics_euler_y_tag    2
#define downlink_proto_IMUMetrics_euler_z_tag    3
#define downlink_proto_IMUMetrics_quat_a_tag     4
#define downlink_proto_IMUMetrics_quat_b_tag     5
#define downlink_proto_IMUMetrics_quat_c_tag     6
#define downlink_proto_IMUMetrics_omega_x_tag    7
#define downlink_proto_IMUMetrics_omega_y_tag    8
#define downlink_proto_IMUMetrics_omega_z_tag    9
#define downlink_proto_IMUMetrics_magnitude_x_tag 10
#define downlink_proto_IMUMetrics_magnitude_y_tag 11
#define downlink_proto_IMUMetrics_magnitude_z_tag 12
#define downlink_proto_IMUMetrics_temperature_tag 13
#define downlink_proto_PowerSupplyMetrics_temperature_v0_tag 1
#define downlink_proto_PowerSupplyMetrics_temperature_v1_tag 2
#define downlink_proto_PowerSupplyMetrics_level_3v3_tag 3
#define downlink_proto_PowerSupplyMetrics_level_5v0_tag 4
#define downlink_proto_SpaceComputerMetrics_power_voltage_tag 1
#define downlink_proto_SpaceComputerMetrics_power_current_tag 2
#define downlink_proto_SpaceComputerMetrics_temperature_die_tag 3
#define downlink_proto_Timestamp_month_tag       1
#define downlink_proto_Timestamp_day_tag         2
#define downlink_proto_Timestamp_year_tag        3
#define downlink_proto_Timestamp_hour_tag        4
#define downlink_proto_Timestamp_minute_tag      5
#define downlink_proto_Timestamp_second_tag      6
#define downlink_proto_SystemMetrics_time_tag    1
#define downlink_proto_SystemMetrics_delayed_tag 2
#define downlink_proto_SystemMetrics_power_supply_tag 3
#define downlink_proto_SystemMetrics_computer_tag 4
#define downlink_proto_SystemMetrics_imu_tag     5
#define downlink_proto_SystemMetrics_digital_tag 6
#define downlink_proto_SystemMetrics_analog_tag  7

/* Struct field encoding specification for nanopb */
#define downlink_proto_DigitalMetrics_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     digital_0,         1) \
X(a, STATIC,   SINGULAR, BOOL,     digital_1,         2) \
X(a, STATIC,   SINGULAR, BOOL,     digital_2,         3) \
X(a, STATIC,   SINGULAR, BOOL,     digital_3,         4) \
X(a, STATIC,   SINGULAR, BOOL,     digital_4,         5)
#define downlink_proto_DigitalMetrics_CALLBACK NULL
#define downlink_proto_DigitalMetrics_DEFAULT NULL

#define downlink_proto_AnalogMetrics_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    analog_0,          1) \
X(a, STATIC,   SINGULAR, FLOAT,    analog_1,          2) \
X(a, STATIC,   SINGULAR, FLOAT,    analog_2,          3) \
X(a, STATIC,   SINGULAR, FLOAT,    analog_3,          4)
#define downlink_proto_AnalogMetrics_CALLBACK NULL
#define downlink_proto_AnalogMetrics_DEFAULT NULL

#define downlink_proto_Timestamp_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    month,             1) \
X(a, STATIC,   SINGULAR, INT32,    day,               2) \
X(a, STATIC,   SINGULAR, INT32,    year,              3) \
X(a, STATIC,   SINGULAR, INT32,    hour,              4) \
X(a, STATIC,   SINGULAR, INT32,    minute,            5) \
X(a, STATIC,   SINGULAR, INT32,    second,            6)
#define downlink_proto_Timestamp_CALLBACK NULL
#define downlink_proto_Timestamp_DEFAULT NULL

#define downlink_proto_PowerSupplyMetrics_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature_v0,    1) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature_v1,    2) \
X(a, STATIC,   SINGULAR, FLOAT,    level_3v3,         3) \
X(a, STATIC,   SINGULAR, FLOAT,    level_5v0,         4)
#define downlink_proto_PowerSupplyMetrics_CALLBACK NULL
#define downlink_proto_PowerSupplyMetrics_DEFAULT NULL

#define downlink_proto_IMUMetrics_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    euler_x,           1) \
X(a, STATIC,   SINGULAR, FLOAT,    euler_y,           2) \
X(a, STATIC,   SINGULAR, FLOAT,    euler_z,           3) \
X(a, STATIC,   SINGULAR, FLOAT,    quat_a,            4) \
X(a, STATIC,   SINGULAR, FLOAT,    quat_b,            5) \
X(a, STATIC,   SINGULAR, FLOAT,    quat_c,            6) \
X(a, STATIC,   SINGULAR, FLOAT,    omega_x,           7) \
X(a, STATIC,   SINGULAR, FLOAT,    omega_y,           8) \
X(a, STATIC,   SINGULAR, FLOAT,    omega_z,           9) \
X(a, STATIC,   SINGULAR, FLOAT,    magnitude_x,      10) \
X(a, STATIC,   SINGULAR, FLOAT,    magnitude_y,      11) \
X(a, STATIC,   SINGULAR, FLOAT,    magnitude_z,      12) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature,      13)
#define downlink_proto_IMUMetrics_CALLBACK NULL
#define downlink_proto_IMUMetrics_DEFAULT NULL

#define downlink_proto_SpaceComputerMetrics_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    power_voltage,     1) \
X(a, STATIC,   SINGULAR, FLOAT,    power_current,     2) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature_die,   3)
#define downlink_proto_SpaceComputerMetrics_CALLBACK NULL
#define downlink_proto_SpaceComputerMetrics_DEFAULT NULL

#define downlink_proto_SystemMetrics_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  time,              1) \
X(a, STATIC,   SINGULAR, BOOL,     delayed,           2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  power_supply,      3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  computer,          4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  imu,               5) \
X(a, STATIC,   OPTIONAL, MESSAGE,  digital,           6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  analog,            7)
#define downlink_proto_SystemMetrics_CALLBACK NULL
#define downlink_proto_SystemMetrics_DEFAULT NULL
#define downlink_proto_SystemMetrics_time_MSGTYPE downlink_proto_Timestamp
#define downlink_proto_SystemMetrics_power_supply_MSGTYPE downlink_proto_PowerSupplyMetrics
#define downlink_proto_SystemMetrics_computer_MSGTYPE downlink_proto_SpaceComputerMetrics
#define downlink_proto_SystemMetrics_imu_MSGTYPE downlink_proto_IMUMetrics
#define downlink_proto_SystemMetrics_digital_MSGTYPE downlink_proto_DigitalMetrics
#define downlink_proto_SystemMetrics_analog_MSGTYPE downlink_proto_AnalogMetrics

extern const pb_msgdesc_t downlink_proto_DigitalMetrics_msg;
extern const pb_msgdesc_t downlink_proto_AnalogMetrics_msg;
extern const pb_msgdesc_t downlink_proto_Timestamp_msg;
extern const pb_msgdesc_t downlink_proto_PowerSupplyMetrics_msg;
extern const pb_msgdesc_t downlink_proto_IMUMetrics_msg;
extern const pb_msgdesc_t downlink_proto_SpaceComputerMetrics_msg;
extern const pb_msgdesc_t downlink_proto_SystemMetrics_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define downlink_proto_DigitalMetrics_fields &downlink_proto_DigitalMetrics_msg
#define downlink_proto_AnalogMetrics_fields &downlink_proto_AnalogMetrics_msg
#define downlink_proto_Timestamp_fields &downlink_proto_Timestamp_msg
#define downlink_proto_PowerSupplyMetrics_fields &downlink_proto_PowerSupplyMetrics_msg
#define downlink_proto_IMUMetrics_fields &downlink_proto_IMUMetrics_msg
#define downlink_proto_SpaceComputerMetrics_fields &downlink_proto_SpaceComputerMetrics_msg
#define downlink_proto_SystemMetrics_fields &downlink_proto_SystemMetrics_msg

/* Maximum encoded size of messages (where known) */
#define downlink_proto_DigitalMetrics_size       10
#define downlink_proto_AnalogMetrics_size        20
#define downlink_proto_Timestamp_size            66
#define downlink_proto_PowerSupplyMetrics_size   20
#define downlink_proto_IMUMetrics_size           65
#define downlink_proto_SpaceComputerMetrics_size 15
#define downlink_proto_SystemMetrics_size        210

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
